customhost = "project2awss2.c2irokidnsne.us-east-1.rds.amazonaws.com"
customuser = "admin"
custompass = "admin123"
customdb = "project2awss2"
custombucket = "project2awss2"
customregion = "us-east-1"
